# Generated by Django 2.2.4 on 2020-04-05 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter the movie name', max_length=250, unique=True)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('CO', 'Comedy'), ('TH', 'Thriller'), ('SH', 'Shit')], max_length=10)),
                ('date_release', models.DateField(help_text='Enter date of movie release')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, help_text='Enter date of addition to database')),
            ],
        ),
    ]
