# Generated by Django 2.2.4 on 2020-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release',
            field=models.CharField(help_text='Enter the initial release year', max_length=4),
        ),
    ]
