# Generated by Django 2.2.4 on 2020-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200407_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(help_text='Enter a value from 1 to 10', max_length=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Enter the movie title', max_length=150),
        ),
    ]
